version: '3'
services:
    mysqldb:
        image: mysql:8.0.29
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT}:${MYSQL_INTERNAL_PORT}
        volumes:
            - db-data:/var/lib/mysql
    # grafana-dashboard:
    #     image: grafana/grafana:8.2.6
    #     environment:
    #         GF_AUTH_DISABLE_LOGIN_FORM: 'true'
    #         GF_AUTH_ANONYMOUS_ENABLED: 'true'
    #         GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    #     ports:
    #         - 3000:${GRAFANA_INTERNAL_PORT}
    #     depends_on:
    #         - mysqldb
volumes:
    db-data:
        driver: local
    grafana-data:
        driver: local